### ISSUE TITLE
download

### ISSUE THREAD

**Issue by ghost** [arsa-hub/arsa#1]
[arsa-ubuntu20-2.7.14.72.tar.gz](https://github.com/arsa-hub/arsa/releases/download/2.7.14.72/arsa-ubuntu20-2.7.14.72.tar.gz)

This binary is 45 Bytes????

**Comment by arsa-hub** [comment]
What binary you ask?

**Comment by ghost** [comment]
Try downloading and extracting the tar.zg file in the link. There are no binaries like in ubuntu 18 version. The tar.gz file is empty.

**Comment by arsa-hub** [comment]
Thank you
[arsa-ubuntu20-2.7.14.72.tar.gz](https://github.com/arsa-hub/arsa/releases/download/2.7.14.72/arsa-ubuntu20-2.7.14.72.tar.gz) update

**Comment by ghost** [comment]
Now good!

Thanks!
